import torch

from base import BaseGanCriterion


class Critic(BaseGanCriterion):
    def calculate(self, z, x, y):
        # Check D with real data
        critic_real = self.model["critic"](x)

        # Check D with fake data generated by G
        gen_x = self.model["generator"](z)
        critic_fake = self.model["critic"](gen_x)

        loss = torch.mean(critic_fake) - torch.mean(critic_real)

        # Return dict for regularization parameters
        reg_params = dict(
            network=self.model['critic'],
            real_data=x,
            fake_data=gen_x,
            critic_real=critic_real,
            critic_fake=critic_fake,
        )

        return loss, reg_params


class Generator(BaseGanCriterion):
    def calculate(self, z, x, y):
        # Check D with real data
        critic_real = self.model["critic"](x)

        # check G net
        gen_x = self.model["generator"](z)
        critic_fake = self.model["critic"](gen_x)

        # calculate criterion
        loss = -torch.mean(critic_fake)

        # Return dict for regularization parameters
        reg_params = dict(
            network=self.model['generator'],
            real_data=x,
            fake_data=gen_x,
            critic_real=critic_real,
            critic_fake=critic_fake,
        )

        return loss, reg_params
